#!/bin/bash

##############################################################################
#
# Aliases (Zach Wilson
#
##############################################################################

# General

## Config
alias .a='v ~/.aliases && source ~/.aliases && echo ".zshrc edited and reloaded."'
alias .f='cd ~/.dotfiles'
alias .fun='v ~/.functions && source ~/.zshrc && echo ".zshrc and .functions edited and reloaded."'
alias .i='v ~/.dotfiles/install.conf.yaml'
alias .k='v ~/.config/kitty/kitty.conf'
alias .n='v ~/.config/nvim/init.lua'
alias .v='v ~/.vimrc'
alias .r='v ~/.config/rofi/config.rasi'
alias .s='source ~/.zshrc'
alias .t='v ~/.tmux.conf'
alias .z='v ~/.zshrc && source ~/.zshrc && echo ".zshrc edited and reloaded."'

## Convenience
alias light='base16_solarized-light'
alias dark='base16_ocean'

# Keyboards
alias kyria='cd /home/zach/qmk_firmware/keyboards/kyria/keymaps/zakrywilson'
alias gergo='cd /home/zach/qmk_firmware/keyboards/gergo/keymaps/zakrywilson'
alias gergoplex='gergo'
alias zmk='cd /home/zach/Development/zmk-config'

## Listing
alias ls='ls --color=auto'
alias l='ls -CF'
alias ll='ls -lF'
alias la='ls -A'
alias lla='ls -lA'

## Misc.
alias c='clear'
alias untar='tar -xvf'

## Applications
alias nvim='~/.local/bin/nvim'
alias v='nvim'
alias grep='grep --color'
alias lg=lazygit

## Be more verbose
alias mv='mv -v'
alias rm='rm -vi'
alias cp='cp -v'
alias ln='ln -v'
